config/routes.rb
Bookswap::Application.routes.draw do

  devise_for :users
  root 'welcome#index'
  namespace :admin do
    get 'home' => 'home#index'
  end
  resources :locations
  resources :books do
    resources :lend_books, only: [:create]
  end
  resources :lend_books
  resources :books do
    collection do
      post :search
    end
  end
  resources :messages
  resources :pages, only: [:index]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :timeoutable
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :lend_books
  has_many :users, through: :lend_books
  validates :title, presence: true, uniqueness: { case_insensitive: true }
  validates :author, presence: true

  def self.search(query)
    joins(:book)
    .where('to_tsvector(books.title || books.author) @@ plainto_tsquery(?)', query)
      .includes(:book, user: [:location])
  end
end

app/models/lend_book.rb
class LendBook < ActiveRecord::Base
  belongs_to :book
  belongs_to :user

  def self.search(query)
    joins(:book)
      .where('to_tsvector(books.title || books.author) @@ plainto_tsquery(?)', query)
      .includes(:book, user: [:location])
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :recipient, class_name: "User"
  belongs_to :sender, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :location
  has_many :lend_books
  has_many :books, through: :lend_books
  has_many :messages, foreign_key: "recipient_id"
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: { case_sensitive: false }

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_action :is_admin?
  def index
  end

  private
  def is_admin?
    if !(current_user && current_user.admin)
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!, only: [:create]



  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :first_name, :last_name, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path, notice: "Successfully added book"
    else
      render 'new'
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
  end

  def search
    @lend_books = LendBook.search(params[:search])
  end

  private

  def filter_books(params)
    Book.search(params[:search])
  end

  def book_params
    params.require(:book).permit(:title, :author)
  end
end

app/controllers/lend_books_controller.rb
class LendBooksController < ApplicationController
  def index
    if user_signed_in?
      @lend_books = current_user.lend_books
    else
      redirect_to user_session_path
    end
  end

  # /books/1/lend_books
  def create
    @book = Book.find(params[:book_id])
    @lend_book = LendBook.new

    @lend_book.user = current_user
    @lend_book.book = @book

    if @lend_book.save
      flash[:notice] = "Successfully added book to bookshelf"
    else
      flash[:alert] = "Failed to add book to bookshelf."
    end

    redirect_to lend_books_path
  end

  def destroy
    @lend_book = LendBook.find(params[:id])
    @lend_book.destroy
    redirect_to lend_books_path
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  def index
    if params[:search].present?
      @locations = Location.near(params[:search], 50, :order => :distance)
    else
      @locations = Location.all
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.user = current_user
    if @location.save
      redirect_to @location, notice: "Successfully saved location"
    else
      render 'new'
    end
  end

  private

  def set_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:address, :latitude, :longitude, :user_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = current_user.messages
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to messages_path, notice: "Successfully sent message!"
    else
      render 'new', notice: "Please enter a valid message"
    end
  end

  private
  def message_params
    recipient = User.where(username: params[:message][:recipient]).first
    params.require(:message).permit(:recipient, :subject, :body).merge(sender: current_user, recipient: recipient)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def show

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def unread_count
    current_user.messages.where(unread: true).count
  end
end

app/views/admin/home/index.html.erb
Welcome Supreme Overlord

app/views/books/index.html.erb
<div class="large-centered large-8 columns">
  <h3 align="center">Books</h3><br><br>
  <table align="center">
    <thead>
        <th>Title</th>
        <th>Author</th>
        <th>I Own This Book</th>
    </thead>

    <tbody>
      <% @books.sort! {|a, b| b.created_at <=> a.created_at }.each do |book| %>
      <%# @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book %></td>
        <td><%= book.author %></td>
        <td class="text-center">
          <%= simple_form_for([book, LendBook.new]) do |f| %>
            <%= f.button :submit, "Add", class: 'button tiny round' %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/new.html.erb
<div class="text-center small-centered large-4 columns">
  <h3>Post a Book</h3><br><br>

  <%= simple_form_for @book do |f| %>
    <%= f.input :title, placeholder: "Title", label: false %>
    <%= f.input :author, placeholder: "Author", label: false %>
    <%= f.button :submit, 'submit', class: 'button'%>
  <% end %>
  </div>
</div>

app/views/books/search.html.erb
<div class="small-centered large-centered large-8 columns">
  <h3 align="center">Search Results</h3><br><br>

  <% if @lend_books.empty? %>
    No results found
  <% else %>
    <table align="center">
      <thead>
        <tr>
          <th>Title</th>
          <th>Author</th>
          <th>Owner</th>
          <th>Location</th>
          <th>Request Book</th>
        </tr>
      </thead>

      <tbody>
        <% @lend_books.each do |lend_book| %>
          <tr>
            <% if lend_book.user_id != current_user.id %>
              <td><%= lend_book.book.title %></td>
              <td><%= lend_book.book.author %></td>
              <td><%= lend_book.user.username %></td>
              <% if user_signed_in? %>
                <td><%= lend_book.user.location.distance_to(current_user.location).round(2) %> miles</td>
              <% else %>
                <td />
              <% end %>
              <td><%= link_to 'Request', new_message_url, class: 'button tiny round' %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>

    <div align="center">
    <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{current_user.location.latitude}%2C#{current_user.location.longitude}" %></div>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="large-centered large-8 columns">
  <h6>title: <%= @book.title %></h6>
  <h6>author: <%= @book.author %></h6>

  <table>
    <thead>
      <th>Book Owners</th>
    </thead>
    <tbody>
      <tr>
        <% @book.users.each do |user| %>
        <td><%= user.username %></td>
      </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->

  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-6 columns">
          <p>© Copyright BookSwapper 2014</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><%= link_to pages_path do %><i class="fa fa-info-circle"></i><% end %></li>
            <li><a href="https://www.linkedin.com/in/lydiawho"><i class="fa fa-linkedin"></i></a></li>
            <li><a href="https://github.com/tomatoturnip"><i class="fa fa-github"></i></a></li>
            <li><a href="http://girltalksincode.tumblr.com/"><i class="fa fa-tumblr"></i></a></li>
            <li><a href="https://twitter.com/Lydia_h0"><i class="fa fa-twitter-square"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav.html.erb
<div class="contain-to-grid sticky">
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "BookSwapper", root_path %></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Left Nav Section -->
      <ul class="left">
        <li class="has-dropdown">
          <a href="#">My BookShelf</a>
          <ul class="dropdown">
            <li><%= link_to "Messages", messages_path, class: 'button', style: 'text-align: left' %></li>
            <li><%= link_to "My Lender List", lend_books_path, class: 'button', style: 'text-align: left' %></li>
            <li><%= link_to "Edit Address", new_location_path, class: 'button', style: 'text-align: left' %></li>
          </ul>
        </li>
        <li class="has-dropdown">
          <a href="#">Books</a>
          <ul class="dropdown">
            <li><%= link_to "Post a Book", new_book_path, class: 'button', style: 'text-align: left' %></li>
            <li><%= link_to "Books", books_path, class: 'button', style: 'text-align: left' %></li>
          </ul>
        </li>
      </ul>

      <!-- Search -->
      <ul class="left">
        <li class="has-form">
          <div class="row collapse buffer">
            <%= form_tag(search_books_path, controller: :books, action: :search, method: :post) do %>
            <%= hidden_field_tag 'search' %>
            <div class="large-12 small-12 columns">
            <%= text_field_tag 'search', params[:query], placeholder: "Find books" %>
           </div>
            <!-- <div class="large-4 small-3 columns"> -->
              <%#= submit_tag 'Search', class: "alert button expand" %>
            <!-- </div> -->
            <% end %>
          </div>
        </li>
      </ul>

      <!-- Top Bar Right Nav Elements -->
      <ul class="right">
        <!-- Divider -->
        <li class="divider"></li>

        <!-- Button -->
        <% if user_signed_in? %>
          <li class="show-for-large-up">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        </li>
        <% else %>
        <li class="show-for-large-up">
          <%= link_to "Log in", new_user_session_path %>
        </li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/_newnav.html.erb
<div class="contain-to-grid sticky">
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "BookSwapper", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li class="has-dropdown">
        <a href="#">My BookShelf</a>
        <ul class="dropdown">
          <li><%= link_to "Messages", messages_path, class: 'button' %></li>
          <li><%= link_to "My Lender List", lend_books_path, class: 'button' %></li>
          <li><%= link_to "Edit Address", new_location_path, class: 'button' %></li>
        </ul>
      </li>
      <li class="has-dropdown">
        <a href="#">Books</a>
        <ul class="dropdown">
          <li><%= link_to "Post a Book", new_book_path, class: 'button' %></li>
          <li><%= link_to "Books", books_path, class: 'button' %></li>
        </ul>
      </li>
    </ul>

    <!-- Search -->
    <ul class="left">
      <li class="has-form">
        <div class="row collapse buffer">
          <%= form_tag(search_books_path, controller: :books, action: :search, method: :post) do %>
          <%= hidden_field_tag 'search' %>
          <div class="large-12 small-12 columns">
          <%= text_field_tag 'search', params[:query], placeholder: "Find books" %>
         </div>
          <!-- <div class="large-4 small-3 columns"> -->
            <%#= submit_tag 'Search', class: "alert button expand" %>
          <!-- </div> -->
          <% end %>
        </div>
      </li>
    </ul>

    <!-- Top Bar Right Nav Elements -->
    <ul class="right">
      <!-- Divider -->
      <li class="divider"></li>

      <!-- Button -->
      <% if user_signed_in? %>
        <li class="show-for-large-up">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      </li>
      <% else %>
      <li class="show-for-large-up">
        <%= link_to "Log in", new_user_session_path %>
      </li>
      <% end %>
    </ul>
  </section>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
    <title><%= content_for?(:title) ? yield(:title) : "BookSwapper" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/nav' %>
    <%= render 'layouts/messages' %>
    <br><br>
    <script src="js/vendor/jquery.js"></script>
    <script src="js/foundation/foundation.js"></script>
    <script src="js/foundation/foundation.orbit.js"></script>

    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag "application" %>


  </body>
</html>

app/views/lend_books/index.html.erb
  <div class="large-centered large-8 columns">
  <h3 align="center"><%= current_user.username %>'s Lender List</h3><br><br>
    <table align="center">

      <thead>
          <th>Title</th>
          <th>Author</th>
          <th>Remove Book</th>
      </thead>

      <tbody>
         <% @lend_books.sort! {|a, b| a.book.title <=> b.book.title }.each do |lend_book| %>
         <%# @lend_books.each do |lend_book| %>
        <tr>
          <td><%= lend_book.book.title %></td>
          <td><%= lend_book.book.author %></td>
          <td><%= link_to "Delete", lend_book_path(lend_book), method: :delete, class: 'button tiny round' %></td>
        </tr>
          <% end %>
      </tbody>
    </table>
    <div align="center">
    <%= button_to "add a book", new_book_path, method: :get, class: 'button' %>
    </div>
</div>

app/views/lend_books/new.html.erb
<div class="text-center small-centered large-4 columns">
  <h3>Post a Book</h3><br><br>

  <%= simple_form_for @book do |f| %>
  <div class="large-4 columns">
    <%= f.input :title %>
    <%= f.input :author %>
    <%= f.button :submit, 'submit' %>
  <% end %>
  </div>
</div>

app/views/locations/index.html.erb
<div class="text-center small-centered large-4 columns">
  <%= form_tag locations_path, :method => :get do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search Near", :name => nil %>
    </p>
  <% end %>
</div>

app/views/locations/new.html.erb
<div class="text-center small-centered large-4 columns">
  <h3>Enter Home Address</h3><br><br>

  <%= simple_form_for @location do |f| %>
    <%= f.input :address %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.button :submit, 'submit', class: 'button' %>
  <% end %>
</div>

app/views/locations/show.html.erb
<div class="text-center small-centered large-4 columns" >

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>

</div>

app/views/messages/index.html.erb
<div class="large-centered large-8 columns">
  <h3 align="center">My Messages</h3><br><br>

  <table align="center">
    <thead>
      <th>Sender</th>
      <th>Subject</th>
      <th>Body</th>
      <th>Reply</th>
    </thead>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.sender.username %></td>
        <td><%= message.subject %></td>
        <td><%= message.body %></td>
        <td><%= link_to "Reply", new_message_path, method: :get, class: 'button tiny round' %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/messages/new.html.erb
<div class="text-center small-centered large-4 columns">
  <h3>Request a Book</h3><br><br>
    <%= simple_form_for @message do |f| %>
      <%= f.input :recipient, as: :string, placeholder: "username" %>
      <%= f.input :subject, placeholder: "book" %>
      <%= f.input :body, placeholder: "meet-location and time" %>

      <%= f.button :submit, 'Send', class: "button" %>
    <% end %>
</div>

app/views/messages/show.html.erb
<h2>Message Inbox</h2>

app/views/pages/index.html.erb
<h1 class="text-center">Lydia H</h1>
<div class="text-center">
<br><br>
<!-- Three-up Content Blocks -->

  <div class="row">
    <div class="large-4 columns">
      <h4>GitHub</h4>
      <h5>github.com/tomatoturnip</h5>
    </div>

    <div class="large-4 columns">
      <h4>LinkedIn</h4>
      <h5>linkedin.com/in/lydiawho</h5>
    </div>
  </div>
<br><br>

app/views/welcome/index.html.erb
<h1 class="text-center">Welcome to the BookSwapper</h1>
<h2 class="text-center">where all your book swapping dreams become a reality</h2>
<br><br><br>

<ul class="example-orbit" data-orbit data-options="timer:true;
timer_speed:2000;
pause_on_hover:false; style=height: 382px;">
  <li>
    <%= image_tag("openbook.jpg", alt: "slide 1")%>
    <div class="orbit-caption">
      1. Search for a book
    </div>
  </li>
  <li>
    <%= image_tag("near.jpg", alt: "slide 2") %>
    <div class="orbit-caption">
      2. Find out who owns the book and lives near you
    </div>
  </li>
  <li>
    <%= image_tag("coffee.jpeg", alt: "slide 3") %>
    <div class="orbit-caption">
      3. Meet up, borrow books, make friends
    </div>
  </li>
</ul>

 <!-- First Band (Image) -->

  <!-- <div class="text-center">
    <div class="row">
      <div class="large-12 columns">
        <%#= image_tag("books.jpeg", width: "500")%>
          <hr>
        </div>
      </div>
    </div> -->
  <!-- Second Band (Image Left with Text) -->

  <div class="row">
    <div class="large-4 columns">
      <%= image_tag("disgusted_girl.jpg") %>
    </div>
    <div class="large-8 columns">
      <h4>Testimonials</h4>
      <div class="row">
        <div class="large-6 columns">
          <p><blockquote><strong>"I got hit on by a creepy older man when we exchanged books last week. I'm not really sure how I feel about this app."</strong><cite>Lindsey Scott</cite></blockquote></p>
        </div>
        <div class="large-6 columns">
          <p><blockquote><strong>"I met up with someone who lives a few blocks away from me, and was able to get the book I've been wanting to read for a long time. That was cool! Until... I realized that sometimes when I look out the window, I see her hiding in a tree, peering at me through binoculars..."</strong><cite>Matthew Pindley</cite></blockquote></p>
        </div>
      </div>
    </div>
  </div>


  <!-- Third Band (Image Right with Text) -->

  <div class="row">
    <div class="large-8 columns">
      <h4>How it works</h4>

      <p>As a book-lender: post a book that you want to lend out.</p>

      <p>As a borrower: search for books that you want. Find books from people who live near you.</p>

      <p>Request the book. Meet up, make friends, and improve your literacy... or in the very least, your personality.</p>

    </div>
    <div class="large-4 columns">
      <%= image_tag("scared_guy.jpeg") %>
    </div>
  </div>